### ISSUE TITLE
Where is the .exe file ?

### ISSUE THREAD

**Issue by ProgrammerPro123456** [KirrimK/RoboKontrol#2]
I'm trying to launch this programm, but when I click on the main file after downloading it, it just opens some code.

WHY IS THERE CODE??? MAKE A FUCKING .EXE FILE AND GIVE IT TO ME. You dumbfucks think that everyone is a developer and understands code. Well I am not and I don't understand it. I only know to download and install applications. SO WHY THE FUCK IS THERE CODE? Make an EXE file and give it to me. STUPID FUCKING SMELLY NERDS

**Comment by ENAC-Robotique** [comment]
Hi,
The instructions are not very clear, but here is what you need to do:
- print the code (on paper)
- start the webcam app on your computer
- show the code to the webcam app

The webcam app will recognize the code and execute it.

**Comment by KirrimK** [comment]
@ENAC-Robotique has provided an appropriate resolution, closing the issue.
